name: gps_map_camera
description: "This app uses an integrated tracking map and camera-based location detection system to accurately identify the userâ€™s current position. By combining GPS tracking with real-time camera input, the app ensures precise location mapping on the field."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  camera: 0.10.3+2
  geolocator: ^13.0.2
  geocoding: ^2.0.5
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image: ^4.0.17
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  share_plus: ^10.0.0
  dio: ^5.4.0
  connectivity_plus: ^6.0.3
  go_router: ^15.1.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^10.1.0
  google_maps_flutter: ^2.5.0
  video_player: ^2.8.6

  ffmpeg_kit_flutter_new_full: ^1.2.0






dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/playstore.png"       # Foreground icon (transparent background)
  adaptive_icon_background: "#ffffff"     # White background for Android
  adaptive_icon_foreground: "assets/logo/playstore.png" # Foreground icon (transparent PNG)
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon/
    - assets/logo/
#     - images/a_dot_burr.jpeg
#     - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
